# Generated by Django 3.2 on 2022-02-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220213_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_full_name',
            new_name='full_name',
        ),
    ]
