# Generated by Django 3.2 on 2022-02-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_auto_20220203_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellar_user_pk', models.CharField(max_length=254)),
                ('date_added_to_cellar', models.DateTimeField(blank=True, null=True)),
                ('quantity_onhand', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cellar_wine_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.wine')),
            ],
        ),
    ]
