# Generated by Django 3.2 on 2022-02-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_rename_cellar_wine_pk_cellaritem_cellar_wine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellaritem',
            old_name='cellar_wine_name',
            new_name='cellar_wine_pk',
        ),
    ]
