# Generated by Django 3.2 on 2022-03-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0005_alter_cellaritem_date_added_to_cellar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellaritem',
            name='cellar_user_pk',
        ),
        migrations.AddField(
            model_name='cellaritem',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
