# Generated by Django 3.2 on 2022-01-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name_plural': 'Body'},
        ),
    ]
