# Generated by Django 3.2 on 2022-01-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220129_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
