# Generated by Django 3.2 on 2022-01-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wine_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='varietal',
            name='alt_url_1',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
