# Generated by Django 3.2 on 2022-02-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_varietal_alt_url_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
