# Generated by Django 3.2 on 2022-02-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_wine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='image',
        ),
    ]
