# Generated by Django 3.2 on 2022-03-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_img_file_name_wine_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='WineBrand',
        ),
    ]
