# Generated by Django 3.2 on 2022-03-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_brand_winebrand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winebrand',
            options={'verbose_name_plural': 'Wine Brands'},
        ),
        migrations.AddField(
            model_name='wine',
            name='puid',
            field=models.CharField(default=1322001, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
