# Generated by Django 3.2 on 2022-03-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220307_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinary',
            name='puid',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='wine',
            name='puid',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='wineaccessory',
            name='puid',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
